spring.application.name=oauth2-jwt


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

#configurar usuario de spring security por defecto
#spring.security.user.name = user
#spring.security.user.password = 1234