spring.application.name=oauth2-jwt


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}



#configurar usuario de spring security por defecto
spring.security.user.name = user
spring.security.user.password = 1234


##base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Visualizar las consultas
spring.jpa.show-sql=true

#Crear/actualiza las tablas de la base de datos. Puede ser update o create.
spring.jpa.hibernate.ddl-auto=create


logging.level.org.springframework.security=DEBUG

jwt.secret.key=soyunafirma
jwt.time.expiration=300000
